src/App.tsx
src/pages/Trip/TripDetail/TripDetail.tsx
src/pages/Trip/TripHome/TripHome.tsx
src/pages/Trip/TripList/TripList.tsx
src/pages/Trip/TripPlan/TripPlan.tsx
src/pages/Trip/index.ts

feat: trip 라우팅 설정

---

src/components/common/Text/Text.styles.ts
src/components/common/Text/Text.tsx
src/components/common/Text/Text.types.ts
src/components/common/Title/Title.styles.ts
src/components/common/Title/Title.tsx
src/components/common/Title/Title.types.ts
src/components/common/index.ts

close #13 
Text 공통 컴포넌트 제작
기본 - 태그: span, 폰트크기: 14px(0.875rem), 폰트굵기: 400, 색상: black
tag속성 - 태그 변경
fontSize속성 - 폰트 크기 변경
fontWeight속성 - 폰트 굵기 변경
color속성 - 글자 색상 변경 ( white, black, gray, primary)

feat: Text 공통 컴포넌트 제작

---

src/components/Home/HomeCreator/HomeCreator.styles.ts
src/components/Home/HomeCreator/HomeCreator.tsx
src/components/Home/HomeCreator/HomeCreatorPost.tsx
src/components/Home/HomeHotplace/HomeHotplace.tsx
src/components/common/Creator/Creator.styles.ts
src/components/common/Creator/Creator.tsx
src/components/common/Creator/Creator.types.ts
src/components/common/Review/Review.styles.ts
src/components/common/Review/Review.tsx
src/components/common/Review/Review.types.ts
src/components/common/Review/ReviewSwiper.tsx
src/pages/Home/Home.tsx

close #37 
- Creator
이거나
- Review
위 참고
데이터가 많네요.. 그래도 prop은 적고 배열 하나 여서 간단합니당
- 노션에 사용법 업데이트 했습니다 !
https://www.notion.so/f2c0283d46c840a5a79070c840af285a
- HomeHotplace는 예외처리 때문에 공통 컴포넌트 적용이 안되더라구요 .. 그래서 준혁님만을 위한 컴포넌트입니다 ㅎㅁㅎ.!

style: Creator/Review UI 공통 컴포넌트화

---

vercel.json

Fix: vercel.json 추가

---

.eslintrc.cjs
src/@types/trip-records.types.ts
src/apis/trip-records.ts
src/components/Trip/TripHome/TripCard/TripCard.tsx
src/components/Trip/TripHome/TripCard/TripCard.types.ts
src/components/Trip/TripHome/TripCarousel/TripCarousel.tsx
src/components/Trip/TripHome/TripCarousel/TripCarousel.types.ts
src/components/Trip/TripHome/TripHomeBody/TripHomeBody.tsx
src/components/Trip/TripList/CardList/CardList.tsx
src/components/Trip/TripList/CardList/CardList.types.ts
src/mocks/handlers.ts
src/pages/Trip/TripDetail/TripDetail.tsx
src/pages/Trip/TripList/TripList.tsx

feat: 여행 일정 후기 API 작성

---

src/hooks/common/useDeleteImages.ts
src/hooks/common/useSubmitImages.ts

refactor: 이미지 업로드 커스텀 훅 수정

---

src/apis/mypage.ts
src/components/MyPage/MyPageComment/MyPageTripRecordReview.tsx
src/components/MyPage/MyPageWishList/MyPageWishList.tsx
src/components/MyPage/MyPageWishList/MyPageWishListMore.tsx
src/components/common/Spots/Spots.tsx
src/components/common/Spots/Spots.types.ts
src/components/common/Spots/SpotsSwiper.tsx
src/constants/MyPage/wishlist.ts

fix: 맡은부분 빌드 에러 해결

---

index.html

fix: Mixed content 에러 해결

---

src/styles/fonts/font.css

refactor: 영문, 숫자 폰트 수정

---

src/@types/mypage.types.ts
src/apis/auth.ts
src/apis/mypage.ts
src/components/MyPage/MyPageNoti/MyPageNoti.tsx
src/components/MyPage/MyPageNoti/MyPageNotiItem.tsx
src/components/MyPage/MyPageNoti/MyPageNotiItem.types.ts
src/components/MyPage/MyPageWishList/MyPageWishList.tsx
src/components/MyPage/MyPageWishList/MyPageWishList.utils.ts
src/components/MyPage/MyPageWishList/MyPageWishListMore.tsx
src/components/common/Spots/Spots.tsx
src/components/common/Spots/Spots.types.ts
src/components/common/Spots/SpotsSwiper.tsx
src/constants/MyPage/notification.ts

close #106 
마이페이지의 알림 기능을 추가하였습니다.

feat: 마이페이지 알림 기능 추가

---

src/App.tsx
src/components/DetailFeed/PlaceReview/PlaceReview.tsx
src/components/Map/Map.tsx
src/components/Trip/TripDetail/Maps/Maps.tsx
src/components/common/PlaceReviewCard/PlaceReviewCard.styles.ts
src/pages/DetailFeed/ReviewComment/ReviewComment.tsx
src/pages/DetailFeed/ReviewComment/ReviewCommentSkeleton.styles.ts
src/pages/DetailFeed/ReviewComment/ReviewCommentSkeleton.tsx
src/pages/DetailFeed/Reviews/Reviews.tsx
src/pages/DetailFeed/Reviews/ReviewsSkeleton.styles.ts
src/pages/DetailFeed/Reviews/ReviewsSkeleton.tsx
src/pages/DetailFeed/TouristSpot/TouristSpot.tsx

close #131
- 여행지 리뷰 페이지 스켈레톤 UI 구현
mui의 skeleton 컴포넌트를 사용해 데이터를 받아오기 전 보여줄 수 있는 스켈레톤 UI를 구현했습니다.

feat: 여행지 리뷰 스켈레톤 UI 구현

---

src/@types/trip-records.types.ts
src/App.tsx
src/components/Trip/TripDetail/TripDescription/TripDescription.tsx
src/components/Trip/TripHome/FloatingButton/FloatingButton.tsx
src/components/Trip/TripHome/ShortsCarousel/ShortsCarousel.tsx
src/components/common/Shorts/ShortsSwiper.tsx
src/utils/videoKey.ts

close #137
- 쇼츠 클릭 시 쇼츠 모달이 뜨도록 구현했습니다.
- 여행 계획 짜기, 여행 후기 작성하기 링크 연결했습니다.
- 여행 일정 복사하기 링크 연결했습니다.

feat: 여행 일정 메인 페이지 쇼츠 모달 구현, Floating 버튼 링크 연결, 여행 일정 복사하기 링크 연결

---

src/components/Trip/TripHome/ShortCard/ShortCard.tsx
src/components/Trip/TripHome/ShortsCarousel/ShortsCarousel.tsx
src/pages/DetailFeed/ShortsList/ShortsList.tsx

refactor: 여행 메인 페이지 쇼츠 수정

---

src/components/Home/HomeHotplace/HomeHotplace.tsx
src/pages/Search/SearchTag.tsx
src/pages/Search/SearchTagExpense.tsx

Feat: key에러 삭제

---

src/@types/cityFeed.types.ts
src/components/DetailFeed/ExchangeRate/ExchangeRate.styles.ts
src/components/DetailFeed/ExchangeRate/ExchangeRate.tsx
src/components/Home/HomeAllCity/HomeCities.tsx
src/components/Home/HomeCreator/HomeCreator.tsx
src/components/Home/HomeHotplace/HomeHotplace.tsx
src/components/Home/HomeShorts/HomeShorts.tsx
src/components/Trip/TripHome/ShortsCarousel/ShortsCarousel.tsx
src/pages/DetailFeed/City/City.tsx
src/pages/Search/Search.styles.ts
src/pages/Search/Search.tsx
src/pages/Search/Search.types.ts
src/pages/Search/SearchNons.tsx
src/pages/Search/SearchTag.tsx
src/pages/Search/SearchTagExpense.tsx

close #147 
- 환율 방향으로 입력 가능하도록 구현했습니다.
- 숫자 이외에 문자는 입력할 수 없도록 방어코드를 작성했습니다.
css 약간 수정하고, 현재 도시 이름 추가했습니다.

refactor: 환율 양뱡향 로직 구현

---

src/components/MyPage/MyPagePlan/MyPagePlanItem.tsx
src/components/MyPage/MyPagePopMenu/MyPagePopMenu.tsx

close #143 
아직 미구현된 링크들은 삭제하였습니다.

fix: 미구현 페이지 링크 삭제

---

src/components/MyPage/MyPageComment/MyPagePlaceReview.tsx
src/components/MyPage/MyPageComment/MyPageTripRecordReview.tsx
src/components/MyPage/MyPagePlan/MyPagePlan.tsx
src/components/MyPage/MyPagePlan/MyPagePlanItem.tsx
src/components/MyPage/MyPageReview/MyPageReview.tsx

close #143 
캐싱 시간으로 인해 최신화 안 되던점 수정,
박수 계산 틀린점 수정

fix: 캐싱시간, 박수 계산 수정

---

src/@types/trip-alldata.types.ts
src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanPostingPlan.tsx
src/components/Trip/TripPlan/TripPlanPostingPlan/TripPlanPostingPlan.types.ts
src/components/Trip/TripPlan/TripPlanPostingPlanRecord/TripPlanPostingPlanRecord.tsx
src/components/Trip/TripPlan/TripPlanPostingReview/TripPlanAddTags/TripPlanAddTags.types.ts

Fix: 태그 미입력시 null값 기본 지정

---

src/components/MyPage/MyPageReview/MyPageReviewItem.tsx
src/components/Trip/TripDetail/Introduction/Introduction.tsx

refactor: 여행 후기 일수 수정

---

src/components/Trip/TripHome/TripCard/TripCard.tsx
src/components/Trip/TripHome/TripHomeBody/TripHomeBody.tsx

refacotr: TripCarousel 일수 수정

---

src/components/DetailFeed/Information/SpotInformationSkeleton.tsx
src/components/DetailFeed/index.ts
src/pages/DetailFeed/TouristSpot/TouristSpot.tsx

refactor: 여행 상세 페이지 스켈레톤 및 에러바운더리 추가

---

src/components/common/Navigation/FeedNav.styles.ts
src/components/common/Navigation/FeedNav.tsx
src/components/common/Navigation/FeedNavSkeleton.tsx
src/components/common/index.ts
src/pages/DetailFeed/City/City.tsx
src/pages/DetailFeed/TouristSpot/TouristSpot.tsx

close #169 
1. 피드 네비게이션바 스켈레톤 추가
2. 비로그인시 저장하기, 일정에 추가하기 렌더링 취소

refactor: 피드 네브바 리팩터링
